[package]
name = "octopus"
version = "0.1.0"
authors = ["borislav nikolov <jack@sofialondonmoskva.com>"]
edition = "2018"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
